### ISSUE TITLE
Is there a way to set the selected tab from C#?

### ISSUE THREAD

**Issue by RichLamb** [Alex-Dobrynin/Xamarin.Controls.TabView#2]
Hi,
Thank you for this fine implementation.  After having troubles with the Xamarin Community TabView, it was a relief to find yours!
I am trying to set the selected tab (index?) from my C# software.  The intent is to show a specific  tab during a specific state of my application.  Is this possible?

Thanks,
Rich Lamb

**Comment by Alex-Dobrynin** [comment]
Ofcourse. Just set tabView.SelectedTabIndex = index;
Or you can use binding from xaml SelectedTabIndex="{Binding Index, Mode=TwoWay}"

**Comment by RichLamb** [comment]
Thanks!  It works, as expected!
Rich
